[package]
name = "SimpleString-Test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_string = { path = "../../runtimes/rust"}
tokio = "*"
tokio-test = "*"
tokio-macros = "*"
