# This workflow runs for every push to main-1.x
name: Push CI

on:
  push:
    branches:
      - main-1.x

jobs:
  pr-populate-dafny-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Populate Dafny versions list
        id: populate-dafny-versions-list
        run: echo "dafny-versions-list=['4.7.0']" >> $GITHUB_OUTPUT
    outputs:
      dafny-version-list: ${{ steps.populate-dafny-versions-list.outputs.dafny-versions-list }}

  push-ci-verification:
    needs: pr-populate-dafny-versions
    strategy:
      fail-fast: false
      matrix:
        dafny-version: ${{ fromJson(needs.pr-populate-dafny-versions.outputs.dafny-version-list) }}
    uses: ./.github/workflows/test_models_dafny_verification.yml
    with:
      dafny: ${{ matrix.dafny-version }}
  push-ci-java:
    needs: pr-populate-dafny-versions
    strategy:
      fail-fast: false
      matrix:
        dafny-version: ${{ fromJson(needs.pr-populate-dafny-versions.outputs.dafny-version-list) }}
    uses: ./.github/workflows/test_models_java_tests.yml
    with:
      dafny: ${{ matrix.dafny-version }}
  push-ci-net:
    needs: pr-populate-dafny-versions
    strategy:
      fail-fast: false
      matrix:
        dafny-version: ${{ fromJson(needs.pr-populate-dafny-versions.outputs.dafny-version-list) }}
    uses: ./.github/workflows/test_models_net_tests.yml
    with:
      dafny: ${{ matrix.dafny-version }}
  push-ci-rust:
    needs: pr-populate-dafny-versions
    strategy:
      fail-fast: false
      matrix:
        # Rust code generation is under development and depends on pending changes to the
        # Dafny Rust code generation, so we test on a specific commit from the feat-rust feature branch instead.
        dafny-version:
          - ab5af65d33b7d44905807f6598b0fbccd5fc39c9
    uses: ./.github/workflows/test_models_rust_tests.yml
    with:
      dafny: ${{ matrix.dafny-version }}
  push-ci-python:
    needs: pr-populate-dafny-versions
    strategy:
      fail-fast: false
      matrix:
        dafny-version: ${{ fromJson(needs.pr-populate-dafny-versions.outputs.dafny-version-list) }}
    uses: ./.github/workflows/test_models_python_tests.yml
    with:
      dafny: ${{ matrix.dafny-version }}